language: python
python:
  - '3.7'

install:
  - pip install coveralls flake8 mypy
  - pip install .

script:
  - flake8 nessclient nessclient_tests
  - mypy --strict nessclient
  - coverage run --source=nessclient setup.py test

after_success: coveralls

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.6

env:
  global:
    secure: EkgMWDOUL+HWt6RauzGhxWD7bK1NmhiqgzFqFMZrkMUdfxLkahs1iStBnJktK3UEBfS4fz6LK+wjIpunVdvne+bFCnB3E2LHvHQ7qUwbxsanVWm93kkS6OEY/iE8VJ3JS8g6ATKoP8r957/jzPLuSVgxkQlXlz9zZbTWsSqUMc8b3Pt6XOUTzXnCmNvtMBMDa6PpRC3qVJvaELEzXb4JFD56tYVWDPQTMOMYVe0BV3oADlFu/Rlqr3wb77AeEMmSfzSc8BQ1t+N8GsDHOOknqcXFO5ze5epy7l8FVW+uWni2WoaIttzCoyfWPTA/JgePl4qtOzczJpMDwAROq3jxCQ5PziD33N9KWuKfAWaXXCBf4HzdLetpB0tluFQEvEDS28KBK5JaLXVjnkE8bymjYgBZPxCi6zm5cUh7a6g0GpWhcdsU76PpeeRrsBSTTHilOvjdmN0xN2U8wCDLspGFiIoteho/xRbAL+x1sFzKXE7d2JRrmxWxx69ktmXiTu+/1lxbLSuMQIhOfIIiSUxfjLwdwABJP3RfU+94cGfwqV9HEQBFTxLMg/hG3DPh8Ke4Y6YxUtNEo6I6LlCWnsXgzAP9tUP4osc3snU/AQlIs6pfk0cEzMD54GeSC/DrXbD/02etMbTcvQ9z2C3rhnvQBzwBH5hWF/g51egvU5MDYA0=
